# Generated by Django 4.1.1 on 2023-04-20 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='createRideLoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autodate', models.DateTimeField(auto_now=True)),
                ('from_address', models.TextField()),
                ('from_lat', models.FloatField(blank=True, null=True)),
                ('from_long', models.FloatField(blank=True, null=True)),
                ('to_address', models.TextField(null=True)),
                ('to_lat', models.FloatField(blank=True, null=True)),
                ('to_long', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('no_of_seats', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('yr', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('fueltype', models.CharField(blank=True, max_length=100, null=True)),
                ('qrlink', models.URLField(blank=True, null=True)),
                ('upid', models.CharField(blank=True, max_length=1000, null=True)),
                ('available_seats', models.IntegerField(blank=True, null=True)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='request_ride_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup', models.CharField(max_length=1000)),
                ('drop', models.CharField(max_length=1000)),
                ('booked', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainride.createrideloc')),
            ],
        ),
    ]
