# Generated by Django 4.1.7 on 2023-03-05 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='createRideLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.TextField()),
                ('from_lat', models.FloatField(blank=True, null=True)),
                ('from_long', models.FloatField(blank=True, null=True)),
                ('to_address', models.TextField(null=True)),
                ('to_lat', models.FloatField(blank=True, null=True)),
                ('to_long', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('no_of_seats', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('yr', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('fueltype', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
