# Generated by Django 4.1.7 on 2023-03-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createrideloc',
            name='autodate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='createrideloc',
            name='date',
            field=models.DateField(),
        ),
    ]
