# Generated by Django 4.1.7 on 2023-03-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainride', '0002_createrideloc_autodate_alter_createrideloc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrideloc',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
