# Generated by Django 4.1.7 on 2023-03-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainride', '0004_createrideloc_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrideloc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
