# Generated by Django 4.1.7 on 2023-03-29 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainride', '0005_alter_createrideloc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_ride_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup', models.CharField(max_length=1000)),
                ('drop', models.CharField(max_length=1000)),
                ('booked', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainride.createrideloc')),
            ],
        ),
    ]
