# Generated by Django 4.1.7 on 2023-03-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainride', '0006_request_ride_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_ride_data',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
