# Generated by Django 4.1.1 on 2023-03-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainride', '0007_request_ride_data_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='createrideloc',
            name='qrlink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createrideloc',
            name='upid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
