# Generated by Django 4.1.1 on 2023-04-20 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import docverify.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='panmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panimg', models.ImageField(blank=True, null=True, upload_to=docverify.models.panmodel.upload_to)),
                ('panno', models.CharField(blank=True, max_length=12, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('did', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='drivingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivinglicimg', models.ImageField(blank=True, null=True, upload_to=docverify.models.drivingmodel.upload_to)),
                ('drivinglicno', models.CharField(blank=True, max_length=12, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('did', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='aadharmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharimg', models.ImageField(blank=True, null=True, upload_to=docverify.models.aadharmodel.upload_to)),
                ('aadharno', models.CharField(blank=True, max_length=12, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
